### ISSUE TITLE
Pressing the "Projects" button sometimes goes to contributor profiles

### ISSUE THREAD

**Issue by pajamaclaws21** [Hyposyn/Hyposyn#1]
After clicking on multiple profiles and pressing Chrome's back button, pressing the "Projects" button goes to the top of the list of profiles instead of completely down to the projects tab.

**Comment by joecooldoo** [comment]
This looks like a bug with the browser, and not the website. It may be the animations when loading on that site screw it up somehow. If you can send a screen recording I will continue to try to assist you.

**Comment by joecooldoo** [comment]
Closing

**Comment by EarthRulerr** [comment]
> This looks like a bug with the browser, and not the website. It may be the animations when loading on that site screw it up somehow. If you can send a screen recording I will continue to try to assist you.

As I did not review the current code fully my reply may be inaccurate* I was not able to replicate this on a Safari browser, assuring that it is I kept a browser issue. A theory for the browser issue is that the browser after clicking the back button and submitting the same url over and over erases the memory of the `<div>` tag or such, causing the browser to send you to the wrong one. Could be wrong, maybe right, if this is the case, I do not believe it is fixable unless one of us is an expert on multi browser implementation of websites, as browsers handle code differently.

**Comment by joecooldoo** [comment]
Ill reopen this and assign @EarthRulerr

**Comment by EarthRulerr** [comment]
> Ill reopen this and assign @EarthRulerr

I’ll look more deeply into how this would work on Chrome and the websites code when I have some more time later.

**Comment by EarthRulerr** [comment]
@pajamaclaws21 Did you click the “Projects” button on the navigation bar at the top then click on peoples profiles and press the back button.

might make more sense:

Did you click the “projects” button then scroll up to “meet our team” and click someone link, then click the back button and instead of being at the “projects” area you were at the “meet our team” area?

**Comment by joecooldoo** [comment]
I honestly think this is a browser issue so I'm going to go ahead and close this.
