### ISSUE TITLE
Netifly Website Heavily Outdated - Done

### ISSUE THREAD

**Issue by EarthRulerr** [Hyposyn/Hyposyn#12]
https://hyposyn.netlify.app is heavily outdated and not complete. The navbar is essentially not existent (only 2 items on it), the "About" section is outdated, the "Meet our Team" section is outdated and bugged (1800s card bugged fixed in later update to Repl), "our projects" is missing SnipOS (to note the text colors are also different from the .repl.co), there is nothing below "our projects" except the text "Links"; and the "Business Hours" section is non existent. Oh, and the favicon (.ico) is outdated/mismatched and the titles of the website are different (Hyposyn Studios vs Hyposyn Home).

How to fix: Update the netifly website or just delete it and use a `.is-an.app` domain.

My proposal: I propose we merge both to a https://is-an.app domain to clean things up.

**Comment by TheOwlCoder** [comment]
_sigh_  i updated the website, now let me go back to sleep
