### ISSUE TITLE
[MAJOR] MOT needs rework! (Dis aligned - miscommunication between os - missing link a/ img)

### ISSUE THREAD

**Issue by EarthRulerr** [Hyposyn/Hyposyn#4]
![IMG_1014](https://user-images.githubusercontent.com/85964403/200860570-de2ea430-b6cc-47c7-8091-dc4bf5302fcc.jpeg)

All usernames are not aligned properly.

IOS devices mis communicate on 1800’s name, **possibly add span between numbers to fix.**
slate’s image and link is missing.
Minor: d4 and 1800’ images could be their Snap! defaults.

**Comment by joecooldoo** [comment]
why don't you try fixing it? :)

**Comment by EarthRulerr** [comment]
> 

Cause I dunno CSS :>

**Comment by joecooldoo** [comment]
this is an html thing

**Comment by EarthRulerr** [comment]
I can fix the span part and stuff but since you made the cards it will be harder for me

**Comment by joecooldoo** [comment]
go ahead and try
ill work it out later

**Comment by EarthRulerr** [comment]
> go ahead and try
> ill work it out later

found another issue and fixed it* also look at the organization thing

**Comment by joecooldoo** [comment]
> look at the organization thing

wdym

**Comment by EarthRulerr** [comment]
> > look at the organization thing
> 
> wdym

Top right of screen next to profile drop down click the “+” drop down > organization

**Comment by joecooldoo** [comment]
do you want me to guy it or smth

**Comment by joecooldoo** [comment]
i made the org

**Comment by joecooldoo** [comment]
everything is fixed
https://github.com/Hyposyn/Hyposyn/commit/c57e339234bd8e9f83e28e44b7db1c483ad9f212
