### ISSUE TITLE
Change font color of branding & link (decoration)

### ISSUE THREAD

**Issue by EarthRulerr** [Hyposyn/Hyposyn#6]
![IMG_1015](https://user-images.githubusercontent.com/85964403/200879075-b3b20da3-30ae-4cb7-9044-62ebedb454a7.jpeg)

**Comment by joecooldoo** [comment]
you can change the link part.
ill update the branding

**Comment by joecooldoo** [comment]
nvm i got it
fixes to logo and CSS https://github.com/Hyposyn/Hyposyn/commit/f69e6acacb2ae3feff81ea0c904d89ea76c049db

**Comment by joecooldoo** [comment]
can you update the replit profile
